/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eventos;

/**
 *
 * @author m1gue
 */
public class eventosJava extends javax.swing.JFrame {

    /**
     * Creates new form eventosJava
     */
    public eventosJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGCarreras = new javax.swing.ButtonGroup();
        txtInfo = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        rdbSoftware = new javax.swing.JRadioButton();
        rdbDiseño = new javax.swing.JRadioButton();
        rdbInd = new javax.swing.JRadioButton();
        rdbMeca = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtInfoMouseEntered(evt);
            }
        });
        txtInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInfoActionPerformed(evt);
            }
        });
        txtInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInfoKeyPressed(evt);
            }
        });

        btnMostrar.setText("Mostar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGCarreras.add(rdbSoftware);
        rdbSoftware.setText("IDS");
        rdbSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbSoftwareActionPerformed(evt);
            }
        });

        btnGCarreras.add(rdbDiseño);
        rdbDiseño.setText("Diseño");
        rdbDiseño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDiseñoActionPerformed(evt);
            }
        });

        btnGCarreras.add(rdbInd);
        rdbInd.setText("Industrial");
        rdbInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbIndActionPerformed(evt);
            }
        });

        btnGCarreras.add(rdbMeca);
        rdbMeca.setText("Mecatronica");
        rdbMeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbMeca)
                    .addComponent(rdbInd)
                    .addComponent(rdbDiseño)
                    .addComponent(rdbSoftware))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(rdbSoftware))
                .addGap(18, 18, 18)
                .addComponent(rdbDiseño)
                .addGap(18, 18, 18)
                .addComponent(rdbInd)
                .addGap(18, 18, 18)
                .addComponent(rdbMeca)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfoActionPerformed
        
        System.out.println(evt.toString());
    }//GEN-LAST:event_txtInfoActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        System.out.println(evt.toString());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void txtInfoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInfoKeyPressed
        System.out.println("Presioné una tecla "+evt.getKeyChar()+" "+evt.getKeyCode());
    }//GEN-LAST:event_txtInfoKeyPressed

    private void txtInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInfoMouseEntered
        System.out.println("X: "+evt.getX()+" Y: "+evt.getY());
        System.out.println(Math.round(Math.random()*100));
    }//GEN-LAST:event_txtInfoMouseEntered

    private void rdbSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSoftwareActionPerformed
        if(rdbSoftware.isSelected()){
            System.out.println("Seleccionó IDS");
        }
        else{
            System.out.println("Sin seleccion");
        }
    }//GEN-LAST:event_rdbSoftwareActionPerformed

    private void rdbDiseñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDiseñoActionPerformed
        if(rdbDiseño.isSelected()){
            System.out.println("Seleccionó Diseño");
        }
        else{
            System.out.println("Sin seleccion");
        }
    }//GEN-LAST:event_rdbDiseñoActionPerformed

    private void rdbIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbIndActionPerformed
        if(rdbInd.isSelected()){
            System.out.println("Seleccionó Industrial");
        }
        else{
            System.out.println("Sin seleccion");
        }
    }//GEN-LAST:event_rdbIndActionPerformed

    private void rdbMecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMecaActionPerformed
        if(rdbMeca.isSelected()){
            System.out.println("Seleccionó Mecatrónica");
        }
        else{
            System.out.println("Sin seleccion");
        }
    }//GEN-LAST:event_rdbMecaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eventosJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eventosJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eventosJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eventosJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eventosJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGCarreras;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JRadioButton rdbDiseño;
    private javax.swing.JRadioButton rdbInd;
    private javax.swing.JRadioButton rdbMeca;
    private javax.swing.JRadioButton rdbSoftware;
    private javax.swing.JTextField txtInfo;
    // End of variables declaration//GEN-END:variables
}
