/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registrousuario2;

/**
 *
 * @author m1gue
 */
public class Modificar extends javax.swing.JFrame {
    Registrar objReg=null;
    Usuario objUsu= null;
    /**
     * Creates new form Modificar
     */
    public Modificar(Registrar objReg, Usuario objUsu){
        this.objUsu=objUsu;
        this.objReg=objReg;
        initComponents();
    }
    
    public Modificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbnGCarrera = new javax.swing.ButtonGroup();
        lblReg = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPnumber = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        rbnIDS = new javax.swing.JRadioButton();
        rbnMecatrónica = new javax.swing.JRadioButton();
        btnMod = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblReg.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblReg.setText("Modificar Usuario");

        lblNombre.setText("Nombre:");

        lblEdad.setText("Edad:");

        lblCorreo.setText("Email:");

        lblTelefono.setText("Telefono:");

        lblCarrera.setText("Carrera:");

        rbnGCarrera.add(rbnIDS);
        rbnIDS.setText("IDS");

        rbnGCarrera.add(rbnMecatrónica);
        rbnMecatrónica.setText("Mecatrónica");

        btnMod.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnMod.setText("Modificar usuario");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPnumber))
                            .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMod)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbnIDS)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbnMecatrónica))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(lblReg))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtName)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtPnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarrera)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbnIDS)
                        .addComponent(rbnMecatrónica)))
                .addGap(27, 27, 27)
                .addComponent(btnMod, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        modificarCambios();
        txtName.setText(objUsu.getNombre());
        txtAge.setText(objUsu.getEdad());
        txtEmail.setText(objUsu.getCorreo());
        txtPnumber.setText(objUsu.getTelefono());
        if(objUsu.getCarrera().equals("IDS")){
            rbnIDS.setSelected(true);
        }else{
            rbnMecatrónica.setSelected(true);
        }
        /*txtName.setText(objReg.enviarNombre());
        txtAge.setText(objReg.enviarEdad());
        txtEmail.setText(objReg.enviarCorreo());
        txtPnumber.setText(objReg.enviarTelefono());
        rbnIDS.setSelected(objReg.enviarIDS());
        rbnMecatrónica.setSelected(objReg.enviarMecatronica());*/
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        modificarCambios();
        //objReg.marcarDatos(txtName.getText(),txtAge.getText(),txtEmail.getText(),txtPnumber.getText(),rbnIDS.isSelected(),rbnMecatrónica.isSelected());
        objReg.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        modificarCambios();
        txtName.setText(objUsu.getNombre());
        txtAge.setText(objUsu.getEdad());
        txtEmail.setText(objUsu.getCorreo());
        txtPnumber.setText(objUsu.getTelefono());
        if(objUsu.getCarrera().equals("IDS")){
            rbnIDS.setSelected(true);
        }else{
            rbnMecatrónica.setSelected(true);
        }
        //objReg.marcarDatos(txtName.getText(),txtAge.getText(),txtEmail.getText(),txtPnumber.getText(),rbnIDS.isSelected(),rbnMecatrónica.isSelected());
        objReg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModActionPerformed
    
    public void modificarCambios(){
        objUsu.setNombre(txtName.getText());
        objUsu.setEdad(txtAge.getText());
        objUsu.setCorreo(txtEmail.getText());
        objUsu.setTelefono(txtPnumber.getText());
        
        if(rbnIDS.isSelected()){
            objUsu.setCarrera("IDS");
        }else if(rbnMecatrónica.isSelected()){
            objUsu.setCarrera("Mecatrónica");
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMod;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.ButtonGroup rbnGCarrera;
    private javax.swing.JRadioButton rbnIDS;
    private javax.swing.JRadioButton rbnMecatrónica;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPnumber;
    // End of variables declaration//GEN-END:variables
}
